name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Вход на сервер по SSH и деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Переходим в директорию с проектом
            cd /root/docker_telegram_bot
            # Обновляем репозиторий
            git pull origin main
            # Останавливаем и удаляем контейнер с именем telegram_bot, если он существует
            docker rm -f telegram_bot || true
            # Собираем новый образ
            docker build -t telegram_bot .
            docker run -d --name telegram_bot --env-file .env -v /root/docker_telegram_bot/bot:/app/bot telegram_bot
